# Ej1_workflow.yml
name: ej1-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Codigo descargar
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar dependencias y test
      run: |
        npm install
        npm test

    - name: Construir imagen
      uses: cloudposse/github-action-docker-compose-test-run@main
